import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Amplify from "aws-amplify";
import config from "../src/aws-exports";
import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

import Link from "next/link";
import styled from "@emotion/styled";
import { useState, useEffect } from "react";
import { Auth } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";

Amplify.configure({
  ...config,
  ssr: true,
});

const Home = (props: any) => {
  console.log("props: ", props);
  const [user, setUser] = useState({
    username: "",
  });

  useEffect(() => {
    // Accessing the user session on the client
    console.log("Auth", Auth);
    Auth.currentAuthenticatedUser()
      .then((user) => {
        console.log("User: ", user);
        setUser(user);
      })
      .catch((err) =>
        setUser({
          username: "",
        })
      );
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {user && user.username} <button onClick={props.signOut}>Sign out</button>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Notes app with Amplify!</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default withAuthenticator(Home);
