import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Amplify from "aws-amplify";
import config from "../src/aws-exports";
import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

import Notes from "../components/Notes";
import Header from "../components/Header";

Amplify.configure({
  ...config,
  ssr: true,
});

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Notes app with Amplify!</h1>
      </main>
      <Notes />
    </div>
  );
};

export default withAuthenticator(Home);
