/* eslint-disable @next/next/no-img-element */
import { FC, useEffect, useState } from "react";
import { useFormik } from "formik";
import Head from "next/head";
import Header from "../../components/Header";
import { updateNote } from "../../src/graphql/mutations";
import Amplify, { API, Storage, withSSRContext } from "aws-amplify";
import config from "../../src/aws-exports";
import { useRouter } from "next/router";
import { GetStaticProps } from "next";
import { getNote, listNotes } from "../../src/graphql/queries";
import { GetNoteQuery, ListNotesQuery, Note } from "../../src/API";
import Link from "next/link";

Amplify.configure({
  ...config,
  ssr: true,
});

interface ICreateNote {
  note: Note;
}

const Create: FC<ICreateNote> = ({ note }) => {
  const router = useRouter();
  const [currentImage, setCurrentImage] = useState("");

  useEffect(() => {
    (async () => {
      if (note?.image) {
        const image = await Storage.get(note.image);
        setCurrentImage(image);
      }
    })();
  }, [note]);

  async function onChange(e: any) {
    if (!e.target.files[0]) return;
    const file = e.target.files[0];
    await Storage.put(file.name, file);
    formik.setValues({
      ...formik.values,
      image: file.name,
    });
  }

  const formik = useFormik({
    initialValues: {
      id: note?.id,
      name: note?.name,
      description: note?.description || "",
      image: currentImage,
    },
    onSubmit: async (values) => {
      try {
        const request = await API.graphql({
          query: updateNote,
          variables: {
            input: values,
          },
        });
        router.push("/");
      } catch (error) {
        console.log(error);
      }
    },
  });

  return (
    <div>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">
        <Link href="/">
          <a className="m-4">{"<-"} Go to Note List</a>
        </Link>
        <h1 className="text-3xl font-bold my-8">Edit Note</h1>
        {!!currentImage && <img src={currentImage} alt="" />}
        <form onSubmit={formik.handleSubmit} className="flex flex-col">
          <label htmlFor="name" className="pb-2 font-bold">
            Name
          </label>
          <input
            id="name"
            name="name"
            type="text"
            placeholder="Write the note title"
            onChange={formik.handleChange}
            value={formik.values.name}
            className="p-2 border mb-4"
          />
          <label htmlFor="description" className="pb-2 font-bold">
            Description
          </label>
          <input
            id="description"
            name="description"
            type="text"
            placeholder="Write the note description"
            onChange={formik.handleChange}
            value={formik.values.description}
            className="p-2 border"
          />

          <input type="file" onChange={onChange} />

          <button type="submit" className="p-4 bg-blue-900 text-white mt-8">
            Update
          </button>
        </form>
      </div>
    </div>
  );
};

export default Create;

export const getStaticPaths: any = async () => {
  const SSR = withSSRContext();
  const notesQuery = await SSR.API.graphql({
    query: listNotes,
  });

  const paths = notesQuery.data.listNotes.items
    .filter((note: any) => note.id)
    .map((note: any) => ({
      params: { id: note?.id },
    }));

  return {
    fallback: true,
    paths,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const SSR = withSSRContext();

  const response = (await SSR.API.graphql({
    query: getNote,
    variables: {
      id: params?.id,
    },
  })) as { data: GetNoteQuery };

  return {
    props: {
      note: response.data.getNote,
    },
  };
};
